[linux_hosts]
novo1 ansible_host=192.168.1.160 ansible_user=novo1
ubuntu ansible_host=192.168.1.162 ansible_user=ubuntu
chromebook ansible_host=192.168.1.153 ansible_user=chromebook

[linux_hosts:vars]
ansible_ssh_private_key_file=~/.ssh/id_ed25519
